docs/api/blockchain-related-methods/api-blockchain-get-software-version.md
docs/api/blockchain-related-methods/api-blockchain-get-total-coin-supply.md
needing-organisation/newdocs/developer-portal/docs/apis/api-blockchain-get-software-version.mdx
needing-organisation/newdocs/developer-portal/docs/apis/api-blockchain-get-total-coin-supply.mdx
products/developer-portal/mkdocs.yml

Add documentation for `GetVersion` and `GetTotalCoinSupplyAsInt` API endpoints.

ZIL-5243: Update documentation for GetVersion and GetTotalCoinSupplyAsInt endpoints.

---

config/workspace-status.py

... when DISABLE_WORKSPACE_STATUS is set.

(feat) US-254: Lie more convincingly about workspace status 

---

products/developer-portal/BUILD

... bazel isn't so great at running containers on OS X.

US-230: [FIX] developer portal containers now run properly on OS X.

---

.github/workflows/ci-on-merge-main-or-release.yml
.github/workflows/cicd.yml

Devex removed from AWS pipeline, added to GCP pipeline.

DEVOPS-904: Devex GCP pipelines

---

docs/zq2/faq.md
docs/zq2/index.md
products/developer-portal/mkdocs.yml

Looks good to me :-) - let's merge so people can see it when they go looking after my talk ..

Add introductory documentation for ZQ2

---

products/bluebell/core/src/lib.rs
products/bluebell/core/src/testing.rs
products/bluebell/core/tests/evm_line_visit_test.rs
products/bluebell/evm_assembly/src/observable_machine.rs

Implements a basic test framework for testing state updates and execution path.

SCIL-50: Feature/test framework

---

products/pdt/.gitignore
products/pdt/Cargo.toml
products/pdt/pdt/src/main.rs
products/pdt/pdtbq/src/meta.rs
products/pdt/pdtbq/src/tracked.rs
products/pdt/pdtparse/src/events.rs
products/pdt/pdtpsql/src/utils.rs

Had to fix minor issues on the code to get it running for BigQuery

ZIL-5421: Minor fixes to get BQ running

---

products/pdt/Cargo.lock
products/pdt/pdt/src/bqimport.rs
products/pdt/pdt/src/importer.rs
products/pdt/pdt/src/importers/transactions.rs
products/pdt/pdt/src/main.rs
products/pdt/pdtbq/Cargo.toml
products/pdt/pdtbq/src/bq.rs
products/pdt/pdtbq/src/bq_client.rs
products/pdt/pdtbq/src/bq_utils.rs
products/pdt/pdtbq/src/lib.rs
products/pdt/pdtbq/src/meta.rs
products/pdt/pdtbq/src/tracked.rs
products/pdt/pdtdb/src/utils.rs
products/pdt/pdtlib/src/exporter.rs
products/pdt/pdtlib/src/incremental.rs
products/pdt/pdtlib/src/lib.rs
products/pdt/pdtlib/src/meta.rs
products/pdt/pdtlib/src/range.rs
products/pdt/pdtlib/src/render.rs
products/pdt/pdtlib/src/sync.rs
products/pdt/pdtlisten/src/lib.rs

There are 2 commits. The first one has the update of gcp client. The second one only fixes linting issues around the codebase. Recommend to only look at the first commit

ZIL-5421: PDT - Update GCP client setup

---

products/pdt/Cargo.lock
products/pdt/Dockerfile

Had to also update cargo.lock as anyhow had changed on previous commit

ZIL-5421: PDT - add rsync to container

---

products/pdt/cd/base/deployment.yaml

Had realised previous PR went into the wrong base branch

ZIL-5434: PDT - Fix manifest 4

---

CODEOWNERS

I clearly don't review all (or even any!) of the PRs in this repository and the notification spam is annoying :)

Remove @JamesHinshelwood as a default CODEOWNER

---

.github/workflows/cicd-prd.yml
.github/workflows/cicd-stg.yml
products/zilliqa-isolated-server/cd/base/kustomization.yaml
products/zilliqa-isolated-server/cd/overlays/staging/app-secret.yaml
products/zilliqa-isolated-server/cd/overlays/staging/backend-config.yaml
products/zilliqa-isolated-server/cd/overlays/staging/certificate.yaml
products/zilliqa-isolated-server/cd/overlays/staging/configmap.yaml
products/zilliqa-isolated-server/cd/overlays/staging/frontend-config.yaml
products/zilliqa-isolated-server/cd/overlays/staging/kustomization.yaml
products/zilliqa-isolated-server/cd/overlays/xcad-production/backend-config.yaml
products/zilliqa-isolated-server/cd/overlays/xcad-production/certificate.yaml
products/zilliqa-isolated-server/cd/overlays/xcad-production/deployment.yaml
products/zilliqa-isolated-server/cd/overlays/xcad-production/frontend-config.yaml
products/zilliqa-isolated-server/cd/overlays/xcad-production/kustomization.yaml

- stg-zilliqa-isolated-server kustomize files.
- xcad-isolated-server kustomize files.

DEVOPS-1128: stg and xcad isolated server envs

---

.github/workflows/cicd-prd.yml
.github/workflows/cicd-stg.yml
products/dev-wallet/BUILD
products/dev-wallet/Makefile
products/dev-wallet/cd/base/configmap.yaml
products/dev-wallet/cd/base/deployment.yaml
products/dev-wallet/cd/base/ingress.yaml
products/dev-wallet/cd/base/kustomization.yaml
products/dev-wallet/cd/base/namespace.yaml
products/dev-wallet/cd/base/svc.yaml
products/dev-wallet/cd/overlays/production/certificate.yaml
products/dev-wallet/cd/overlays/production/frontend-config.yaml
products/dev-wallet/cd/overlays/production/kustomization.yaml
products/dev-wallet/cd/overlays/staging/certificate.yaml
products/dev-wallet/cd/overlays/staging/frontend-config.yaml
products/dev-wallet/cd/overlays/staging/kustomization.yaml

Dev-wallet CD kustomize files and image build in CI pipeline.

DEVOPS-1042: dev-wallet migration to gcp

---

products/dev-wallet/cd/overlays/staging/kustomization.yaml

Correct IP for stg (dev-wallet) fix.

DEVOPS-1042: dev-wallet stg ip fix

---

docs/developers/getting-started/dev-started-env.md

Update the community testnet and devnet environment documentation adding the reference to the running version and the persistence folder name.

feat(US-331): update testnet and devnet documentation

---

docs/developers/getting-started/dev-started-env.md
docs/staking/staking-phase-1.1/ssn-operators/staking-ssn-setup.md

Updates the documentation for the Community Testnet and Public devnet including the new reward parameter smart contract address for the testnet and the version and folder version.
Adds the SSN minimum system requirements.

US-332: update the documentation for ZQ1 v930rc19

---

docs/developers/getting-started/dev-started-env.md

Update the environment information for the mainnet:
1. Add the mainnet reward control contract address
2. Add the mainnet persistence folder name
3. Add the mainnet persistence bucket

DEVOPS-1185: mainnet v9.3.0 information update

---

.bazelignore
contracts/experimental/ERC20ProxyForZRC2/.env.example
contracts/experimental/ERC20ProxyForZRC2/.gitignore
contracts/experimental/ERC20ProxyForZRC2/README.md
contracts/experimental/ERC20ProxyForZRC2/contracts/ScillaConnector.sol
contracts/experimental/ERC20ProxyForZRC2/contracts/ZRC2ProxyForZRC2.sol
contracts/experimental/ERC20ProxyForZRC2/hardhat.config.ts
contracts/experimental/ERC20ProxyForZRC2/package.json
contracts/experimental/ERC20ProxyForZRC2/scripts/deploy.ts
contracts/experimental/ERC20ProxyForZRC2/tsconfig.json
pnpm-lock.yaml
pnpm-workspace.yaml

New experimental contract for EVM compatible ZRC2 proxy token. Making ZRC2 compatible with EVM and interoperable.
Example project bootstrapped using standard hardhat boilerplate.
The code should align with https://github.com/Zilliqa/Zilliqa/pull/3916

ZIL-5536: New ERC20ProxyForZRC2 contract example

---

.github/workflows/cicd-stg.yml
products/bridge/bridge-validators/.dockerignore
products/bridge/bridge-validators/Cargo.lock
products/bridge/bridge-validators/Cargo.toml
products/bridge/bridge-validators/Dockerfile
products/bridge/bridge-validators/README.md
products/bridge/bridge-validators/docker-compose.yaml
products/bridge/bridge-validators/infra/config-leader.toml
products/bridge/bridge-validators/infra/config.toml
products/bridge/bridge-validators/src/client.rs
products/bridge/bridge-validators/src/main.rs
products/bridge/bridge-validators/src/p2p_node.rs
products/bridge/bridge-validators/src/validator_node.rs
products/bridge/smart-contracts/script/relay.zqt.s.sol

PR ready, just waiting to test dockerisation

ZIL-5548: Bridge - Dockerise + Kademlia Bootstrap + Config Import Refactor

---

contracts/experimental/ERC20ProxyForZRC2/hardhat.config.ts
contracts/experimental/ERC20ProxyForZRC2/package.json
contracts/experimental/ERC20ProxyForZRC2/scripts/deploy.ts
pnpm-lock.yaml

Updated some missing changes that did not allow the contract to be deployed properly

ZIL-5548: Update ERC20ProxyForZRC2 contracts

---

.github/workflows/ci-bridge.yml
products/bridge/bridge-web/package-lock.json
products/bridge/bridge-web/package.json
products/bridge/bridge-web/src/App.tsx
products/bridge/bridge-web/src/config/config.ts
products/bridge/bridge-web/src/index.css
products/bridge/bridge-web/src/main.tsx

ZIL-5550: Bridge Add UI improvements

---

products/bridge/bridge-web/src/App.tsx

Fix approval gas on zrc2proxy txns

ZIL-5550: Bridge Web fix approval gas

---

products/bridge/bridge-web/src/App.tsx
products/bridge/bridge-web/src/config/config.ts
products/bridge/bridge-web/src/config/wallet.ts

Fix `VITE_ENV=PROD` in production

ZIL-5550: Prod env vars + fix allowances and balance

---

products/bridge/smart-contracts/contracts/periphery/TokenManagerV2/LockAndReleaseTokenManagerUpgradeableV2.sol
products/bridge/smart-contracts/contracts/periphery/TokenManagerV2/MintAndBurnTokenManagerUpgradeableV2.sol
products/bridge/smart-contracts/contracts/periphery/TokenManagerV2/TokenManagerFees.sol
products/bridge/smart-contracts/contracts/periphery/TokenManagerV2/TokenManagerUpgradeableV2.sol
products/bridge/smart-contracts/foundry/test/periphery/TokenManagerV2/LockAndReleaseTokenManagerUpgradeableV2.t.sol
products/bridge/smart-contracts/foundry/test/periphery/TokenManagerV2/MintAndBurnTokenManagerUpgradeableV2.t.sol

New version of contracts to include:
- New fee system
- Pausable transfers

ZIL-5557: XBridge - TokenManagerUpgradeableV2 Contracts

---

products/bridge/bridge-web/src/App.tsx
products/bridge/bridge-web/src/abi/TokenManager.ts

ZIL-5558: XBridge UI Add pausing integration

---

products/bridge/bridge-validators/config.local.toml
products/bridge/bridge-validators/src/client.rs
products/bridge/bridge-validators/src/validator_node.rs

NonceManagerMiddleware needs to be on wrapped on top of SingerMiddleware...

ZIL-5558: Update nonce manager

---

products/bridge/bridge-validators/src/bridge_node.rs

For some reason the bsc rpc returns triplicated relay events, even when i request for one. Not sure why, and combined with the new nonce manager it would submit 3 in a row

ZIIL-5558: Prevent repeated relay nonces from being submitted

---

products/bridge/smart-contracts/README.md
products/bridge/smart-contracts/package-lock.json
products/bridge/smart-contracts/script/bsc-testnet/bridgeTokens.s.sol
products/bridge/smart-contracts/script/bsc-testnet/deployCoreUpgradeable.s.sol
products/bridge/smart-contracts/script/bsc-testnet/pauseBridge.s.sol
products/bridge/smart-contracts/script/bsc-testnet/setChainGatewayOnTokenManager.s.sol
products/bridge/smart-contracts/script/bsc-testnet/unpauseBridge.s.sol
products/bridge/smart-contracts/script/bsc-testnet/upgradeTokenManagerV3.s.sol
products/bridge/smart-contracts/script/bsc/deployCoreUpgradeable.s.sol
products/bridge/smart-contracts/script/bsc/pauseBridge.s.sol
products/bridge/smart-contracts/script/bsc/setChainGatewayOnTokenManager.s.sol
products/bridge/smart-contracts/script/bsc/transferOwnership.s.sol
products/bridge/smart-contracts/script/bsc/unpauseBridge.s.sol
products/bridge/smart-contracts/script/bsc/updateValidators.s.sol
products/bridge/smart-contracts/script/bsc/upgradeTokenManagerV3.s.sol
products/bridge/smart-contracts/script/zq-testnet/deployCoreUpgradeable.s.sol
products/bridge/smart-contracts/script/zq-testnet/pauseBridge.s.sol
products/bridge/smart-contracts/script/zq-testnet/setChainGatewayOnTokenManager.s.sol
products/bridge/smart-contracts/script/zq-testnet/unpauseBridge.s.sol
products/bridge/smart-contracts/script/zq-testnet/upgradeTokenManagerV3.s.sol
products/bridge/smart-contracts/script/zq/deployCoreUpgradeable.s.sol
products/bridge/smart-contracts/script/zq/pauseBridge.s.sol
products/bridge/smart-contracts/script/zq/setChainGatewayOnTokenManager.s.sol
products/bridge/smart-contracts/script/zq/transferOwnership.s.sol
products/bridge/smart-contracts/script/zq/unpauseBridge.s.sol
products/bridge/smart-contracts/script/zq/updateValidators.s.sol
products/bridge/smart-contracts/script/zq/upgradeTokenManagerV3.s.sol

Scripts for deploying TokenManagerV3 and new ChainGatewayUpgradeable and TokenManagerUpgradeable contracts for bsc and zq mainnet and testnets
Also contains some for transferring ownership of the contracts

US-0: XBridge SC: deployment scripts for v3 contracts

---

products/bridge/smart-contracts/script/config.ts
products/bridge/smart-contracts/task/bridge.ts

Script to get historica relayed events

US-0: XBridge SC - Script to get historical relayed events

---

products/zillion/src/components/home.tsx

ZIL-5574: Update Plunderswap name case

---

products/bluebell/Cargo.lock
products/bluebell/core/src/formatter.rs

This reverts commit ee9543fec7943523ae896a91a697de5691b7fcab.

Revert "US-338: Update bluebell dependencies. (#522)"

---

products/bridge/bridge-web/src/App.tsx
products/bridge/bridge-web/src/index.css

Dropdown added. It shows all the tokens from the config
I bridged TSLM to BSC and back to ZQ with this bridge.

APT-937: Bridge token dropdown

---

products/zillion/src/components/ssn-table.tsx

(add): google ssn node

---

products/eth-spout/src/main.rs

Removes the NonceManager and changes the provider instantiation removing the dependencies from a working API.
This allows us to upgrade the network without restart the faucet and also simplify the faucet installation process making it completely decoupled from the RPC endpoint.

(fix): remove eth-spout dependency from the api endpoint to fetch the chain-id

---

products/zillion/src/components/ssn-table.tsx

This reverts commit 5c5006ac82d0ce7fe4ccff699bdc2546140d858a.

Revert "Add cardano ssn (#730)"

---

.github/workflows/cicd-prd.yml
.github/workflows/cicd-stg.yml

Removing CI/CD references but keeping the source files.

feat: DEVOPS-2169 decommission isolated-server
