.github/workflows/ci-on-merge-main-or-release.yml
.github/workflows/ci-on-pr-bazel-test-mac.yml
.github/workflows/ci-on-pr-bazel-test-ubuntu-22.04.yml
config/gcp_cs_cache.py

This PR introduces the remote cache to bazel to solve the size limit issue we were facing on the default GHA cache (10GB) and speed up the overall monorepo build process.
It uses a Google Cloud Storage bucket hosted on the GCP Zilliqa organization as cache storage.
The integration has been built leveraging oicd and federated workload identities. No static and insecure keys have been sprawl across.
The required configuration parameters workload_identity_provider and google service account id have been exposed as Organization environment variable for a simpler integration with the multiple bazel worklaods.
The authentication to google has been managed with the GHA google-github-actions/auth@v1.

DEVOPS-833: migrate bazel cache to GCS

---

docs/api/introduction/api-endpoints.md

eth_subscribe is stateful and so needs to hit the same endpoint successive times.
To this end the current solution is that you need to use http://evm-api-filters.zilliqa.com/ on mainnet for example if you want to guarantee this.

Amend api docs to indicate there are multiple endpoints

---

products/pdt/Cargo.lock
products/pdt/pdt/Cargo.toml
products/pdt/pdtbq/Cargo.toml
products/pdt/pdtdb/Cargo.toml
products/pdt/pdtlib/Cargo.toml
products/pdt/pdtlisten/Cargo.toml
products/pdt/pdtlisten/src/listener.rs

The pods running in kubernetes keep on restarting because of `Tx Block does not exist` error thrown by the RPC that's used to collect the blocks. This is usually a momentary issue arising when the RPC is delayed. This can be solved through a graceful approach by retrieving the block on the next poll attempt

US-317: PDT - Update listen error handling + update deps

---

products/pdt/cd/base/configmap.yaml
products/pdt/cd/overlays/staging/configmap.yaml
products/pdt/pdt/src/main.rs
products/pdt/pdtlib/src/context.rs

This affects only the cronjob run daily on the PDT, as it needs to download the persistence on a daily basis. The `listen` command and pods are unaffected.

ZIL-5490: PDT Migrate Testnet Persistence to GCP 

---

products/governance-api/cd/overlays/production/secrets-app.yaml

Typo in the vault name for prod apps.

DEVOPS-1040: correct vault for snapshot-api

---

products/developer-portal/cd/base/deployment.yaml
products/devex/cd/base/deployment.yaml
products/governance-api/cd/base/deployment.yaml
products/governance-snapshot/cd/base/deployment.yaml
products/neo-savant/cd/base/deployment.yaml
products/zillion/cd/base/deployment.yaml
products/zilliqa-isolated-server/cd/base/deployment.yaml

Proposed request and memory limits for the following apps depending on their max. average memory usage:
- developer-portal (avg. max 20MB -> min: 100 MB max: 200 MB)
- devex (avg. max 20MB -> min: 100 MB max: 200 MB)
- governance-api (avg. max 200MB -> min: 300 MB max: 500 MB)
- governance-snapshot (avg. max 5MB -> min: 100 MB max: 200 MB)
- neo-savant-ide (avg. max 20MB -> min: 100 MB max: 200 MB)
- xcad-isolated-server (avg. max 100MB -> min: 200 MB max: 400 MB)
- zillion (avg. max 20MB -> min: 100 MB max: 200 MB)
- zilliqa-isolated-server (avg. max 100MB -> min: 200 MB max: 400 MB)

DEVOPS-1149: memory limits for devex, governance, zillion, neo-savant and isolated-server

---

products/neo-savant/.env_dev

Since the domain https://nucleus-server.zilliqa.com/ was unreachable and no ECS service was running, we decomissioned the URL and propose to update the neo-savant env dev environment config (which is the only reference to the nucleus-server).

DEVOPS-1172: remove nucleus-server decomissioned url from neo-savant dev env

---

products/dev-wallet/Dockerfile
products/dev-wallet/nginx/default.conf

Added a custom configuration for nginx to allow permalinks such as https://dev-wallet.zilliqa.com/faucet

DEVOPS-1184: nginx custom config for dev-wallet

---

products/bridge/smart-contracts/contracts/core/ChainGateway.sol
products/bridge/smart-contracts/contracts/core/Registry.sol
products/bridge/smart-contracts/contracts/core/Relayer.sol
products/bridge/smart-contracts/contracts/core/ShardGateway.sol
products/bridge/smart-contracts/foundry/test/core/Relayer.t.sol
products/bridge/smart-contracts/foundry/test/periphery/TokenBridge.integration.t.sol

New `Registry` contract allows the owner to add and remove addresses from the a set of whitelist contracts in the registry. This is used by inheriting the abstract contract `Registry` and implementing the necessary functions to manage the registry. The implementation is done in the `Relayer` contract which is inherited into `ChainGateway`

ZIL-5548: Check sender contracts are registered on the ChainGateway

---

products/bridge/smart-contracts/contracts/periphery/BridgedToken.sol
products/bridge/smart-contracts/foundry/test/periphery/BridgedToken.t.sol

This extended version of the contract is taken from: [SwitcheoTokenETH](https://github.com/Zilliqa/switcheo-tradehub-eth/blob/master/contracts/tokens/SwitcheoTokenETH.sol). It has also been refactored to support the newer version of solidity which is used by all other parts of the contract, including to new ways of error handling. 
The ZilBridge, uses the `transfer` capability to mint new tokens if it does not currently hold any. Essentially it is a `MintAndLock` bridge rather than our `MintAndBurn` bridge. With this capability with we could eventually migrate the token to zilbridge by assigning the corresponding `lockProxyAddress` with `setLockProxyAddress` and renounce ownership over the contract to disable the `mint` and `burn` external functions.
NB: once deployed the owner will be …

ZIL-5548: Bridge: extend BridgeToken to be eventually compatible with ZilBridge

---

products/bridge/bridge-validators/config.toml
products/bridge/bridge-validators/infra/cd/base/config-leader.toml
products/bridge/bridge-validators/infra/cd/base/config.toml
products/bridge/bridge-validators/infra/config-leader.toml
products/bridge/bridge-validators/infra/config.toml
products/bridge/bridge-validators/src/validator_node.rs

Because gas estimations given by `eth_estimateGas` being too tight for transactions that call scilla interoperability precompiles. Thus I had to manually query gas estimate and also multiply it for buffer. 30% more was the option I chose, that is what is also adopted by foundry by default
Also updated the addresses of the bridge to match the new contracts

ZIL-5554: Bridge Update gas estimation for ZQ networks on validators

---

products/bridge/bridge-web/src/App.tsx

I removed the "Testnet" suffixes for the network names in these images. I figured this is what we'll do it mainnet anyway.
Desktop
iPhone SE
Pixel 7

Improve display on smaller screens

---

products/bridge/bridge-web/src/App.tsx

Had to fix an issue where the event occurs before the the event listener is able to pick up when bridging from ZQ -> BSC.
Thus we verify if the event has occurred before the event listener begins

Fix UI where event is emitted before listener

---

products/bridge/bridge-validators/config.local.toml
products/bridge/bridge-validators/config.toml
products/bridge/bridge-validators/infra/config-leader.toml
products/bridge/bridge-validators/infra/config.toml
products/bridge/bridge-validators/src/block.rs
products/bridge/bridge-validators/src/client.rs
products/bridge/bridge-validators/src/main.rs

Make the validator fetch the validator_manager addresses when it boots up instead of hardcoding it. It is always stored in the chain_gateway anyways.

US-0: XBridge Validator - Fetch validator_manager_address on initialize

---

products/bridge/bridge-validators/abi/ChainGateway.json
products/bridge/bridge-validators/abi/ValidatorManager.json
products/bridge/bridge-web/src/abi/ChainGateway.ts
products/bridge/bridge-web/src/abi/TokenManager.ts
products/bridge/bridge-web/src/config/config.ts

Backwards compatible update on the abis.
Also migrates FE to use new chaingateway and validatormanager addresses
New mainnet contracts have also been added

US-0: XBridge FE/BE update abis and addresses for new contracts

---

.github/workflows/cicd-prd.yml
.github/workflows/cicd-stg.yml
products/multisig/Makefile
products/zillion/Makefile

- Registry Cache (v2) pipelines added to the CI pipelines.
- Removed unused variables from Makefiles of multisig and zillion.

DEVOPS-1298: registry cache in CI pipelines

---

.github/workflows/cicd-stg.yml

Name should match the matrix reference in a pipeline.

DEVOPS-1298 bridge-validator ref in stg ci pipeline

---

products/bridge/bridge-web/src/config/config.ts

Adding test tokens deployed on ZQ and BSC testnets to the config to enable them in the x-bridge UI

DEVOPS-1369: update config.ts

---

.github/workflows/cicd-stg.yml

Adding decryption secrets into the staging CICD.
Those secrets are already provided to prd pipeline https://github.com/Zilliqa/zilliqa-developer/blob/main/.github/workflows/cicd-prd.yml/#L202-L219

APT-1040: build time staging decryption secrets added to CICD

---

products/bridge/smart-contracts/test/periphery/TokenManagerUpgradeTest/TokenManagerUpgradeTest.t.sol

Fixes the following x-bridge tests that were failing:
```
Encountered 8 failing tests in test/periphery/TokenManagerUpgradeTest/TokenManagerUpgradeTest.t.sol:TokenManagerUpgradeTest
[FAIL. Reason: Multiple matching artifacts found] test_upgrade_add_erc7201_non_compliant_contract_inheritance_to_end() (gas: 11060)
[FAIL. Reason: Multiple matching artifacts found] test_upgrade_change_order_of_inheritance() (gas: 9149)
[FAIL. Reason: Multiple matching artifacts found] test_upgrade_inherit_new_erc7201_compliant_contract_to_end() (gas: 9347)
[FAIL. Reason: Multiple matching artifacts found] test_upgrade_inherit_new_erc7201_compliant_contract_to_middle() (gas: 9083)
[FAIL. Reason: Multiple matching artifacts found] test_upgrade_new_getter_for_existing_variable() (gas: 9457)
[FAIL. Reason: …
```

fixed failing upgradeability tests

---

package.json
products/devex/src/utils/Utils.tsx

Devex crashes if we supply gas outside the number limits of 2^53. The fix is to pass a string instead of a number in big number constructor in function `qaToZil`

Fix devex to not crash for high gas txn

---

products/eth-spout/src/main.rs

PR #699 attempted to remove the startup-time dependency on the API by moving the point at which we get the chain ID to transaction creation time.
However, this wasn't valid because the signer needs to be configured with the correct chain ID. Instead, we wrap our provider in a `tokio::sync::OnceCell` and lazily initialise it.
This means the signer is initialised with the result of the call from `eth_chainId`, but we don't need to make this call until someone uses the faucet.

Fix `DifferentChainID` error

---

products/eth-spout/Cargo.lock

quick fix to get z2 running. `eth-spout` currently broken in main with:
```
error[E0282]: type annotations needed for `Box<_>`
--> /home/tw/.cargo/registry/src/index.crates.io-6f17d22bba15001f/time-0.3.34/src/format_description/parse/mod.rs:83:9
|
83 |     let items = format_items
|         ^^^^^
...
86 |     Ok(items.into())
|              ---- type must be known at this point
|
= note: this is an inference error on crate `time` caused by an API change in Rust 1.80.0; update `time` to version `>=0.3.35` by calling `cargo update`
```
See `note:` in the bottom of the error message

chore: update deps to fix eth-spout

---

products/zillion/src/saga/stakingSaga.ts
products/zillion/src/util/calculator.ts
products/zillion/src/zilliqa-api.ts

The web console now contains entries that start with `[BlockchainRead]`. For each blockchain read operation, there is one entry like that. It shows the query, how long it took, and whether it was successful.
Works when running with `npm run dev`

APT-1688: Logging for blockchain read access operations improved

---

products/zillion/cd/overlays/staging/kustomization.yaml
products/zillion/src/util/calculator.ts
products/zillion/src/util/reward-calculator.ts

Turns out, at least for now, the ZQ2 always returns `_balance` field in the response. Zillion reward calculation logic depends on the response being null if there is no data for given user.
Fixed by adjusting response before pushing it to the rewards logic.
Additionally, there was a minor bug in the deployment file.
Run locally. Works on Mainnet and Protomainnet.

APT-1689: Fix for _balance field in ZQ2 substate query response
